kind: Deployment
apiVersion: apps/v1
metadata:
  name: projectname
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: projectname
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 50m
              memory: 50Mi