apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: projectname
    app.kubernetes.io/component: projectname
    app.kubernetes.io/instance: projectname
    app.kubernetes.io/part-of: projectname-app
  name: projectname
spec:
  port:
    targetPort: 80-tcp
  to:
    kind: Service
    name: projectname
    weight: 100
  wildcardPolicy: None