apiVersion: v1
kind: Service
metadata:
  labels:
    app: mdsregistryapi
    app.kubernetes.io/component: mdsregistryapi
    app.kubernetes.io/instance: mdsregistryapi
    app.kubernetes.io/part-of: mdsregistryapi-app
  name: mdsregistryapi
spec:
  ports:
  - name: 443-tcp
    port: 443
    protocol: TCP
    targetPort: 443
  - name: 80-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: mdsregistryapi
    deploymentconfig: mdsregistryapi
  sessionAffinity: None
  type: ClusterIP